package com.spamfilter.adminclient.db;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ListMutationsTest {

    @Test
    void blocklistAddShouldRemoveWhitelistEntryFirst() throws SQLException {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:h2:mem:cross-list;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        config.setUsername("sa");
        config.setPassword("");

        try (HikariDataSource ds = new HikariDataSource(config)) {
            createSchema(ds);
            BlocklistRepository blocklistRepository = new BlocklistRepository(ds);
            WhitelistRepository whitelistRepository = new WhitelistRepository(ds);

            whitelistRepository.add("2000", "Alias", "Trusted", "admin@example.com");
            blocklistRepository.addAndRemoveOpposite("2000", "spam source", null);

            assertEquals(1, blocklistRepository.count());
            assertEquals(0, whitelistRepository.count());
        }
    }

    @Test
    void whitelistAddShouldRemoveBlacklistEntryFirst() throws SQLException {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:h2:mem:cross-list-2;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        config.setUsername("sa");
        config.setPassword("");

        try (HikariDataSource ds = new HikariDataSource(config)) {
            createSchema(ds);
            BlocklistRepository blocklistRepository = new BlocklistRepository(ds);
            WhitelistRepository whitelistRepository = new WhitelistRepository(ds);

            blocklistRepository.add("2000", "spam source", null);
            whitelistRepository.addAndRemoveOpposite("2000", "Alias", "Trusted", "admin@example.com");

            assertEquals(0, blocklistRepository.count());
            assertEquals(1, whitelistRepository.count());
        }
    }

    private static void createSchema(HikariDataSource ds) throws SQLException {
        try (Connection c = ds.getConnection();
             PreparedStatement blocklist = c.prepareStatement(
                     "CREATE TABLE blocklist (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, msisdn VARCHAR(255) NOT NULL UNIQUE, reason VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, expires_at TIMESTAMP)");
             PreparedStatement whitelist = c.prepareStatement(
                     "CREATE TABLE whitelisted_senders (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sender_id VARCHAR(255) NOT NULL UNIQUE, alias_name VARCHAR(255), description VARCHAR(255), added_by VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)")) {
            blocklist.executeUpdate();
            whitelist.executeUpdate();
        }
    }
}
